# 7. Initial Risk Register

This register records project-specific risks identified at M1. Each risk has a unique ID, a specific description, a probable cause, a probability and impact rating, a priority level, a mitigation action, a contingency action, an owner, and a status. The register is a live artefact which will be reviewed and updated at every milestone.

**Highest-priority risk for M1 defence:** RISK-001 (Scope Creep: Critical).
**Reason:** CivicConnect is replacing an informal process. Stakeholders are likely to request additional features once they see the system taking shape. Without a controlled baseline and a formal change process, scope growth will silently consume the team's capacity and delay delivery.

**Priority scale:** Critical = must act now, High = act before next milestone, Medium = monitor and plan, Low = monitor

| Risk ID | Description | Cause | Prob. | Impact | Priority | Mitigation | Contingency | Owner | Status |
|---|---|---|---|---|---|---|---|---|---|
| RISK-001 | Scope creep, stakeholders request new features after scope is baselined | No formal change process; stakeholders may assume the team can add features without impact | High | High | Critical | Maintain a controlled scope baseline from M1. All new requests go through a formal change request and impact analysis before acceptance. | Formally decline or defer the request. Record the decision in the Engineering Decision Log. Escalate to lecturer if unresolved. | Team Lead | Open |
| RISK-002 | Team member becomes unavailable for a significant period | Illness, academic pressure, or personal circumstances reducing a member's contribution | Medium | High | High | All members understand the full project, not only their own tasks. Shared code reviews and documentation reduce single-member dependency. | Redistribute work using the team working agreement. Log the variance. Notify the lecturer if a milestone deadline is at risk. | All | Open |
| RISK-003 | Role-Based Access Control (RBAC) implemented incorrectly | Access rules not clearly defined in requirements, or not tested per role | Medium | High | High | Define access rules per role (Requester, Staff, Management) in M1 requirements. Test each role in isolation during M3. | Restrict affected features to read-only or disable them. Log as a defect and apply a fix before any further testing or release. | Security lead | Open |
| RISK-004 | Sensitive request data exposed through weak authentication or insecure endpoints | Security treated as a later concern; authentication not enforced on all data routes | Low | High | High | Security requirements defined in M1. All data endpoints require authentication. No secrets committed to the repository. | Disable affected features immediately. Apply and verify fix. Record incident in the Risk Register as a materialised risk. | All | Open |
| RISK-005 | Team selects an unfamiliar technology stack, causing delays due to the learning curve | Stack chosen for interest rather than team readiness; learning time underestimated | Medium | Medium | Medium | Stack decision deferred to M2 with team capability assessment as a required input. Prefer tools the team has already used. | Reduce scope to core features. Record the schedule impact as a variance. Document the trade-off in the Decision Log. | Infrastructure lead | Open (deferred to M2) |
| RISK-006 | Free-tier hosting or database limits reached, causing unexpected outage or cost | Platform limits not checked before selection; usage grows beyond the free tier during testing | Medium | Medium | Medium | Research and document free-tier limits for all candidate platforms in M2 decision records. Build within those limits. | Switch to a lower-cost alternative. Reduce data retention or feature scope as needed. Document the change. | Lead | Open |
| RISK-007 | Requester notification delivery fails; users do not receive status updates on their requests | Notification system not tested end-to-end; reliance on third-party email/SMS service without fallback | Medium | Medium | Medium | Define a notification NFR with a measurable acceptance criterion. Test delivery in staging before release. | Provide in-app status visibility as a fallback so requesters can still check their request. Log failures for review. | Developer | Open |
| RISK-008 | AI-generated artefacts (requirements, test cases, code) used without adequate human review | Time pressure; team trusts AI output without checking accuracy against project context | Medium | Medium | Medium | Every AI contribution is logged in the AI Usage Register. A team member reviews and verifies the output before it enters any controlled artefact. | Remove the unverified artefact. Replace with a human-authored version. Update the AI Usage Register to record what was rejected and why. | All | Open |
